# Generated by Django 4.1.4 on 2022-12-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
