# Generated by Django 4.1.4 on 2022-12-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddd', '0002_remove_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Название лекарства')),
                ('auth_user', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(default='Сформирован', max_length=50)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Когда последний раз обновлялась информация?')),
            ],
        ),
    ]
